--SQL QUERY BASED ANALYSIS

--SQL SYNTHAX AND QUERIES

SELECT *
FROM Amazon2

ALTER TABLE Amazon2
ALTER COLUMN Selling_Price Decimal(10.2)

ALTER TABLE Amazon2
ALTER COLUMN Tax_5 Decimal(10,2)

---TOTAL REVENUE GENERATED BY EACH BRANCH
SELECT Branch,
SUM((Selling_Price * Quantity) + Tax_5) AS Total_Revenue
FROM Amazon2
Group By Branch

--TOP 3 PRODUCTS LINES BY REVENUE
SELECT TOP 3 Product_Line,
SUM((Selling_Price * Quantity) + Tax_5) AS Total_Revenue
FROM Amazon2
Group By Product_Line
Order By Total_Revenue DESC

---TOTAL REVENUE BY CUSTOMER TYPE
SELECT Customer_Type,
SUM((Selling_Price * Quantity) + Tax_5) AS Total_Revenue
FROM Amazon2
Group By Customer_Type

--- AVERAGE RATING FOR EACH PRODUCT LINE
SELECT Product_Line,
AVG(Rating) AS Average_Rating
FROM Amazon2
Group By Product_Line

ALTER TABLE Amazon2
ALTER COLUMN Tax_5 Decimal(10,2)

--REVENUE GENERATED PER PAYMENT METHOD

SELECT Payment,
SUM((Selling_Price * Quantity) + Tax_5) AS Total_Revenue
FROM Amazon2
Group BY Payment
Order BY Total_Revenue DESC

---DAILY REVENUE TREND
SELECT DATE,
SUM((Selling_Price * Quantity) + Tax_5) AS Total_Revenue
FROM Amazon2
Group BY DATE
Order BY DATE DESC


